name:  Create Submission

# Trigger on any push with a git tag
# To create a git tag, run the following commands on the branch you wish to release:
#   git tag 1.0.0.0
#   git push origin --tags
on:
  push:
    tags:
      - '*'

jobs:
  build_zip:
    name: Create Submission
    runs-on: ubuntu-latest

    env:
      Target_Name: qwrx21-psc
      Files: ${{ join(fromJSON('[
        "Solution/step-1.cpp",
        "Solution/step-2.cpp",
        "Solution/step-3.cpp",
        "Solution/step-4.cpp",
        ]'), ' ') }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Prepare Directory
        run: mkdir tmp

      - name: Copy Files
        run:  cp ${{env.Files}} ./tmp

      # LATEX
      #- name: Build Latex
      #  uses: xu-cheng/latex-action@v2
      #  with:
      #    root_file: |
      #      Report/report.tex

      #- name: Copy Data Report 
      #  run:  cp report.pdf ./tmp/

      - name: Add Version File
        run: printf 'Submission built on %s from:\ngit hash: %s\nversion: %s' '$(date +'%Y-%m-%d')' '${{ github.ref }}' '$GITHUB_SHA' >> VERSION.md

      # ZIP final solution
      - name: ZIP Files
        run: zip ${{env.Target_Name}}-${{ github.ref }}.zip *
        working-directory: ./tmp

      
      # Create release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name:  ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload as asset
      - name: Upload as an asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./tmp/${{env.Target_Name}}
          asset_name: ${{env.Target_Name}}
          asset_content_type: application/zip
      
      # Save temp artifacts
      #- name: Save Artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: ${{env.Target_Name}}
      #    path: ./tmp/${{env.Target_Name}}